### ISSUE TITLE
What about octave?

### ISSUE THREAD

**Issue by stefano2734** [josephcarmack/convection_diffusion_2d#1]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info.
if unknown, untested with octave is also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by josephcarmack** [comment]
Yes it was originally written and tested in octave when I wrote this 6 years ago. First comment in the one file of source code indicates that.

**Comment by stefano2734** [comment]
You can also take this information about Octave in Readme and as search word like CFD or FEM.

tested with Version x.yz would also be nice for reader and potential user.

thanks.
